FROM python:3.11-slim
WORKDIR /app
COPY flask-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY flask-api/ .
EXPOSE 5050
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "--workers", "2", "--timeout", "300", "app:create_app()"]
